# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'day26.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_openfile = QtWidgets.QPushButton(self.centralwidget)
        self.button_openfile.setGeometry(QtCore.QRect(230, 560, 93, 28))
        self.button_openfile.setObjectName("button_openfile")
        self.button_pause = QtWidgets.QPushButton(self.centralwidget)
        self.button_pause.setGeometry(QtCore.QRect(560, 560, 93, 28))
        self.button_pause.setObjectName("button_pause")
        self.button_play = QtWidgets.QPushButton(self.centralwidget)
        self.button_play.setGeometry(QtCore.QRect(440, 560, 93, 28))
        self.button_play.setObjectName("button_play")
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(670, 560, 93, 28))
        self.button_stop.setObjectName("button_stop")
        self.label_filepath = QtWidgets.QLabel(self.centralwidget)
        self.label_filepath.setGeometry(QtCore.QRect(20, 600, 451, 51))
        self.label_filepath.setObjectName("label_filepath")
        self.label_framecnt = QtWidgets.QLabel(self.centralwidget)
        self.label_framecnt.setGeometry(QtCore.QRect(20, 490, 211, 71))
        self.label_framecnt.setObjectName("label_framecnt")
        self.label_videoframe = QtWidgets.QLabel(self.centralwidget)
        self.label_videoframe.setGeometry(QtCore.QRect(60, 110, 560, 315))
        self.label_videoframe.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_videoframe.setObjectName("label_videoframe")
        self.slider_videoframe = QtWidgets.QSlider(self.centralwidget)
        self.slider_videoframe.setGeometry(QtCore.QRect(240, 510, 801, 22))
        self.slider_videoframe.setOrientation(QtCore.Qt.Horizontal)
        self.slider_videoframe.setObjectName("slider_videoframe")
        self.label_videoframe_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_videoframe_2.setGeometry(QtCore.QRect(660, 110, 560, 315))
        self.label_videoframe_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_videoframe_2.setObjectName("label_videoframe_2")
        self.button_openfile_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_openfile_2.setGeometry(QtCore.QRect(330, 560, 93, 28))
        self.button_openfile_2.setObjectName("button_openfile_2")
        self.label_filepath_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_filepath_2.setGeometry(QtCore.QRect(660, 600, 451, 51))
        self.label_filepath_2.setObjectName("label_filepath_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 560, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(660, 50, 560, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_openfile.setText(_translate("MainWindow", "Openfile"))
        self.button_pause.setText(_translate("MainWindow", "Pause"))
        self.button_play.setText(_translate("MainWindow", "Play"))
        self.button_stop.setText(_translate("MainWindow", "Stop"))
        self.label_filepath.setText(_translate("MainWindow", "file path:"))
        self.label_framecnt.setText(_translate("MainWindow", "current_frame/total_frame"))
        self.label_videoframe.setText(_translate("MainWindow", "video_player_1"))
        self.label_videoframe_2.setText(_translate("MainWindow", "video_player_2"))
        self.button_openfile_2.setText(_translate("MainWindow", "Openfile_2"))
        self.label_filepath_2.setText(_translate("MainWindow", "file path_2:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
